#!/bin/bash

# Restore the data that was backed up in 010-backup-data.

set -e

mysql ykksm < data-backup/ykksm.sql
mysql ykval < data-backup/ykval.sql

cp data-backup/users /etc/freeradius/users
cp data-backup/ykrlm-config.cfg /etc/yubico/rlm/ykrlm-config.cfg 
cp data-backup/ykmapping /etc/yubico/rlm/ykmapping

rm data-backup -R
