#!/usr/bin/perl -w

#use strict;
use warnings;

use Test::More tests => 2;
use Test::Exception;

like(`radtest user2 pass2 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Accept/, 'user2 pass2');

like(`radtest user2 pass3 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Reject/, 'user2 pass3');
