#!/usr/bin/perl -w

use strict;
use warnings;

use Test::More tests => 13;
use Test::Exception;

like(`radtest user1 pass1cccccccccccbtjhlvlgnjbetljghhldtjnetitcefbvt 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Accept/, 'provision OTP');

like(`radtest user1 pass1cccccccccccbtdlvnjrirlvurifltccivrjfeeiigrhl 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Accept/, 'append OTP to password');

like(`radtest user1cccccccccccbvevcrklddjnbjhclhhdbngihiicvvlbi pass1 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Accept/, 'append OTP to username');

like(`radtest user1cccccccccccbvevcrklddjnbjhclhhdbngihiicvvlbi pass1 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Reject/, 'replay OTP to username');

like(`radtest user1 pass1cccccccccccbvevcrklddjnbjhclhhdbngihiicvvlbi 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Reject/, 'replay OTP to password');

like(`radtest user1 pass1cccccccccccdutfiljtbignbgckhgdtfigbdricugdrv 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Reject/, 'valid unknown OTP');

like(`radtest user1 pass1cccccccccccbutfiljtbignggckhgdtfigbdricugddd 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Reject/, 'invalid OTP');

like(`radtest user1 pass1 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Accept/, 'do not require OTP');

#Disable auto provisioning
`echo "\\\$allow_auto_provisioning = 0;" >> /etc/yubico/rlm/ykrlm-config.cfg`;
`service freeradius restart`;

like(`radtest user2 pass2 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Accept/, 'no OTP provisioned');

like(`radtest user2cccccccccccdevhrjfhjvivcldffttudhngrctjhlhuf pass2 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Reject/, 'unprovisioned OTP');

#Manually provision:
`echo "user2:cccccccccccd" >> /etc/yubico/rlm/ykmapping`;

like(`radtest user2cccccccccccdfhgrbtkeurfgjuiingirikvncejnktit pass2 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Accept/, 'manually provisioned OTP');

like(`radtest cccccccccccdlvigeledtrhnjfdibigjfcnhbilrfheb pass2 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Accept/, 'userless login');

#Disable userless login:
`echo "\\\$allow_userless_login = 0;" >> /etc/yubico/rlm/ykrlm-config.cfg`;
`service freeradius restart`;

like(`radtest cccccccccccdiufijhvbfnlclvbtrjlduegcujfdikuf pass2 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Reject/, 'disallowed userless login');
