#!/usr/bin/perl -w

# Copyright (c) 2013 Yubico AB
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#   * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#
#   * Redistributions in binary form must reproduce the above
#     copyright notice, this list of conditions and the following
#     disclaimer in the documentation and/or other materials provided
#     with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

use strict;
use warnings;

use Test::More tests => 9;
use Test::Exception;

# user1 provisioned, user2 not. Auto-provisioning is off.
# level 0
`echo "user1:cccccccccccb" > /etc/yubico/rlm/ykmapping`;
`echo "\\\$security_level = 0;" >> /etc/yubico/rlm/ykrlm-config.cfg`;
`service freeradius restart`;

like(`radtest user1 pass1 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Accept/, '0: user1 has no OTP');

like(`radtest user2 pass2 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Accept/, '0: user2 without OTP');

like(`radtest user1 pass1cccccccccccbrkcdnlnjglvhggvvthvtnjcbkcbgdnci 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Accept/, '0: user1 with OTP');

# level 1
`sed -i 's/security_level = 0/security_level = 1/g' /etc/yubico/rlm/ykrlm-config.cfg`;
`service freeradius restart`;

like(`radtest user1 pass1 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Challenge/, '1: user1 has no OTP');

like(`radtest user2 pass2 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Accept/, '1: user2 without OTP');

like(`radtest user1 pass1cccccccccccbvidrncnrueuvdjvcteghundndiuujukb 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Accept/, '1: user1 with OTP');

# level 2
`sed -i 's/security_level = 1/security_level = 2/g' /etc/yubico/rlm/ykrlm-config.cfg`;
`service freeradius restart`;

like(`radtest user1 pass1 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Challenge/, '2: user1 has no OTP');

like(`radtest user2 pass2 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Challenge/, '2: user2 without OTP');

like(`radtest user1 pass1cccccccccccbidneikekrhhdenuhhrbculeultvecjbe 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Accept/, '2: user1 with OTP');

