#!/usr/bin/perl -w

use strict;
use warnings;

use Test::More tests => 9;
use Test::Exception;

# user1 provisioned, user2 not. Auto-provisioning is off.
# level 0
`echo "user1:cccccccccccb" > /etc/yubico/rlm/ykmapping`;
`echo "\\\$security_level = 0;" >> /etc/yubico/rlm/ykrlm-config.cfg`;
`service freeradius restart`;

like(`radtest user1 pass1 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Accept/, '0: user1 has no OTP');

like(`radtest user2 pass2 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Accept/, '0: user2 without OTP');

like(`radtest user1 pass1cccccccccccbrkcdnlnjglvhggvvthvtnjcbkcbgdnci 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Accept/, '0: user1 with OTP');

# level 1
`sed -i 's/security_level = 0/security_level = 1/g' /etc/yubico/rlm/ykrlm-config.cfg`;
`service freeradius restart`;

like(`radtest user1 pass1 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Challenge/, '1: user1 has no OTP');

like(`radtest user2 pass2 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Accept/, '1: user2 without OTP');

like(`radtest user1 pass1cccccccccccbvidrncnrueuvdjvcteghundndiuujukb 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Accept/, '1: user1 with OTP');

# level 2
`sed -i 's/security_level = 1/security_level = 2/g' /etc/yubico/rlm/ykrlm-config.cfg`;
`service freeradius restart`;

like(`radtest user1 pass1 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Challenge/, '2: user1 has no OTP');

like(`radtest user2 pass2 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Challenge/, '2: user2 without OTP');

like(`radtest user1 pass1cccccccccccbidneikekrhhdenuhhrbculeultvecjbe 127.0.0.1 0 testing123`,
	qr/rad_recv: Access-Accept/, '2: user1 with OTP');

